### ISSUE TITLE
Is there any way to contact you?

### ISSUE THREAD

**Issue by jungha17** [developer0hye/2018-Turtlebot3-Autorace-ROBIT#1]
Hello, I am a student preparing for the Turtlebot Auto Race.
I'm using nuc, but the Turtlebot emanual is a Raspberry Pi standard, so I'm having a hard time.
I have a question for you about this, is there any way to contact you?
Sorry for the inconvenience and thank you.

**Comment by developer0hye** [comment]
@jungha17 
Sorry for the late reply.

It took a long time since I developed this project and I just worked on a computer vision task.

Now I am not working on robotics, and even I forgot knowledge related to ROS.

So I can't help you with connecting Turtlebot and nuc.
I wish you all great success in your work.
